version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: senai_postgres
      POSTGRES_USER: senai_postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - senai_postgres:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "5693:5693"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_ROLE: ${ADMIN_ROLE}
      ADMIN_EMAIL: ${ADMIN_EMAIL}

volumes:
  senai_postgres: